server:
  port: 8888
spring:
  application:
    name: management-system-config-server
  profiles:
    active: vault
  # Message broker required for busrefresh
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh,mappings,env
  endpoint:
    health:
      show-details: always