server:
  port: 8888
spring:
  application:
    name: management-system-config-server
  profiles:
    active: vault
management:
  endpoints:
    web:
      exposure:
        include: health,info,busrefresh
  endpoint:
    health:
      show-details: always

