spring:
  cloud:
    config:
      server:
        vault:
          host: ${VAULT_HOST:127.0.0.1}
          port: 8200
          scheme: http
          backend: secret
          default-key: ${VAULT_KEY:management-system}
          profile-separator: ","
          kv-version: 2
          skip-ssl-validation: true
          timeout: 5
          authentication: TOKEN
          token: ${ROOT_TOKEN}
          order: 1
  #          namespace: null
