services:
  vault:
    build: .
    container_name: management-system-vault
    ports:
      - "8200:8200"
    volumes:
      - ./data:/vault/data
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: management-system-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
#    networks:
#      - app-network
    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5