spring:
  application:
    name: management-system-desktop-client
  main:
    banner-mode: off
    # Disable web environment (disabled by default if no WebMVC or WebFlux)
    web-application-type: none
  threads:
    virtual:
      enabled: false
  http:
    clients:
      connect-timeout: 5s
      read-timeout: 30s
app:
  title: Management System
  base-url: "http://localhost:5000"
  # Theme color variant: light, dark
  theme-variant: dark
  # Theme names: Flat, macOS, IntelliJ, Cyan-Purple, Material, Solarized-Carbon, Orange-Ocean
  theme-name: Material
flat:
  inspector:
    enabled: true
  # Enable app icon for Linux (default is false)
  linux-decorations:
    enabled: true
screen:
  preferred-resolution:
    width: 1024
    height: 800
  minimum-resolution:
    width: 800
    height: 500